### ISSUE TITLE
Improve English base language

### ISSUE THREAD

**Issue by periclesJ** [bothub-it/bothub#45]
**Description:**  
Would be awesome if this base could receive some improvement, small changes on the analyzed such as a simple coma, makes a severe intent change on this language.

For example on the (https://bothub.it/johncordeiro/binary/) if you test "no whats this" we receive "negative (74.7%)", but if you try "no, whats this" you will receive "affirmative (64.5%)".

PS.: Set English as analyzed language.
> **Browser:** browser  
> **OS:** operating system  
> **Authenticated**: Yes/No  
> **URL**: https://bothub.it/...

**Comment by douglasppaz** [comment]
@johncordeiro Can you help here?
